### ISSUE TITLE
Good first Issues

### ISSUE THREAD

**Issue by gdrbacca** [gdrbacca/03-github-blog#2]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
 

### Search before asking

- [x] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues) and found no similar issues.
 
 
### Describe the proposal
 
 These issues are a great way to get started with a project. Any contribution is important for the Uniffle Commuinity. If the issues have been assigned to others, but there isn't any progress for more than 3 months. You can ask committers or collaborators to assign it to you, too. 
 The steps of contribution is as below: https://github.com/apache/incubator-uniffle/blob/master/CONTRIBUTING.md
 
### Task list

 Code Style Improvements
 If you don't read the code of Uniffle but you have some experience about Java. These issues are suitable for you.
- [x] https://github.com/apache/incubator-uniffle/issues/851
- [x] https://github.com/apache/incubator-uniffle/issues/363
- [x] https://github.com/apache/incubator-uniffle/issues/532

 
Simple Tasks
If you don't realize the code of Uniffle and want to realize this project by some tasks. These issues are suitable for you.
- [ ] https://github.com/apache/incubator-uniffle/issues/1020
- [x] https://github.com/apache/incubator-uniffle/issues/974
- [x] https://github.com/apache/incubator-uniffle/issues/460
- [x] https://github.com/apache/incubator-uniffle/issues/333
- [ ] https://github.com/apache/incubator-uniffle/issues/138
- [ ] https://github.com/apache/incubator-uniffle/issues/313
- [x] https://github.com/apache/incubator-uniffle/issues/1119
- [x] https://github.com/apache/incubator-uniffle/issues/1108
- [x] https://github.com/apache/incubator-uniffle/issues/1157

 CI Improvement
 If you're not familiar about Uniffle but have some experience about Github Actions. These issues are suitable for you.
- [ ] https://github.com/apache/incubator-uniffle/issues/1096
 
Documents
If you don't have much experience about Java and Uniffle but want to contribute to this project. You can try to improve the documents of this project.
- [x] https://github.com/apache/incubator-uniffle/issues/1094

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!
